name: Production Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  production-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Build production app
        run: npm run build

      - name: Serve app in background
        run: npx serve -s dist -l 5000 &
      
      - name: Wait for server to start
        run: sleep 10

      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          BASE_URL: http://localhost:5000
